syntax = "proto3";
package tablet;
option go_package = "github.com/Anmol202005/VScale/proto/tablet";
message QueryRequest {
    string sql = 1;
    int64 transaction_id = 2;
}
message QueryResponse {
    repeated QueryResult results = 1;
    int64 transaction_id = 2;
}
message QueryResult {
    string sql = 1;
    repeated string columns = 2;
    repeated Row rows = 3;
    int64 rows_affected = 4;
}
message Row {
    repeated string values = 1;
}
message HealthRequest {}
message HealthResponse {
    bool healthy = 1;
    string cell = 2;
    uint32 uid = 3;
    string keyspace = 4;
    string shard = 5;
    string tablet_type = 6;
    string alias = 7;
    int32 max_conns = 8;
}
message PrepareRequest {
    string sql = 1;
    int64 transaction_id = 2;
}
message PrepareResponse {
    bool prepared = 1;
    string error = 2;
    QueryResult result = 3;
}
message CommitRequest {
    int64 transaction_id = 1;
}
message CommitResponse {
    bool committed = 1;
    string error = 2;
}
message RollbackRequest {
    int64 transaction_id = 1;
}
message RollbackResponse {
    bool rolled_back = 1;
    string error = 2;
}
service TabletService {
    rpc Execute(QueryRequest)
        returns (QueryResponse);
    rpc Prepare(PrepareRequest)
        returns (PrepareResponse);
    rpc Commit(CommitRequest)
        returns (CommitResponse);
    rpc Rollback(RollbackRequest)
        returns (RollbackResponse);
    rpc Health(HealthRequest)
        returns (HealthResponse);
}